language: python
os: linux
env:
  - MPLBACKEND=Agg
install:
  - pip install -r requirements.txt
  - pip install .
before_script: cd tests
script: pytest -v
jobs:
  include:
    - name: "Python 2.7"
      python: 2.7
    - name: "Python 3.5"
      python: 3.5
    - name: "Python 3.6"
      python: 3.6
    - stage: format
      python: 3.6
      install: pip install autopep8
      before_script: " "
      script:
        - python setup.py check_format --directory docs --file-type python
        - python setup.py check_format --directory hep_spt --file-type python
        - python setup.py check_format --directory tests --file-type python
