language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - MPLBACKEND=Agg
# Command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# Move to the tests directory
before_script:
  - cd tests
# Command to run tests
script: pytest -v

# Add more stages
jobs:
  include:
    - stage: format
      name: "Check format"
      python: 3.6
      install: pip install autopep8
      script:
        - python setup.py check_format --directory docs --file-type python
        - python setup.py check_format --directory hep_rfm --file-type python
        - python setup.py check_format --directory tests --file-type python
